
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Wed Jul 09 2025 14:25:36 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Awardpage extends ContentItem {
    public bannerheading!: Elements.TextElement;
    public bannersubheading!: Elements.TextElement;
    public bannerimage!: Elements.AssetsElement;
    public ctabuttonname!: Elements.TextElement;
    public ctabuttonlink!: Elements.TextElement;
    public aboutheading!: Elements.TextElement;
    public aboutdescription!: Elements.TextElement;
    public timelineheading!: Elements.TextElement;
    public timelineitems!: Elements.LinkedItemsElement<ContentItem>;
    public categoriesheading!: Elements.TextElement;
    public categoriesitems!: Elements.LinkedItemsElement<ContentItem>;
    public faqheading!: Elements.TextElement;
    public faqitems!: Elements.LinkedItemsElement<ContentItem>;
    public seometadataPagetitle!: Elements.TextElement;
    public seometadataMetatitle!: Elements.TextElement;
    public seometadataMetadescription!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'seometadata__pagetitle') {
                    return 'seometadataPagetitle';
                }
                if (elementName === 'seometadata__metatitle') {
                    return 'seometadataMetatitle';
                }
                if (elementName === 'seometadata__metadescription') {
                    return 'seometadataMetadescription';
                }
                return elementName;
            })
        });
    }
}
