
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Wed Feb 19 2025 09:29:00 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Conferencedate extends ContentItem {
    public datestring!: Elements.TextElement;
    public date!: Elements.DateTimeElement;
    public heading!: Elements.TextElement;
    public content!: Elements.RichTextElement;
    public sessionitems!: Elements.LinkedItemsElement<ContentItem>;
}
