
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Sun Jul 06 2025 18:27:55 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Homepagesaudi extends ContentItem {
    public bannerheading!: Elements.TextElement;
    public bannersubheading!: Elements.RichTextElement;
    public bannerimage!: Elements.AssetsElement;
    public seometadataPagetitle!: Elements.TextElement;
    public seometadataMetatitle!: Elements.TextElement;
    public seometadataMetadescription!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'seometadata__pagetitle') {
                    return 'seometadataPagetitle';
                }
                if (elementName === 'seometadata__metatitle') {
                    return 'seometadataMetatitle';
                }
                if (elementName === 'seometadata__metadescription') {
                    return 'seometadataMetadescription';
                }
                return elementName;
            })
        });
    }
}
