
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Sun Jul 06 2025 18:27:55 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Menu extends ContentItem {
    public brandlogo!: Elements.AssetsElement;
    public homelink!: Elements.TextElement;
    public menuitems!: Elements.LinkedItemsElement<ContentItem>;
    public date!: Elements.TextElement;
    public venue!: Elements.TextElement;
    public poweredbylogo!: Elements.AssetsElement;
}
