
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Wed Feb 19 2025 09:29:00 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Sessionitem extends ContentItem {
    public name!: Elements.TextElement;
    public time!: Elements.TextElement;
    public starttime!: Elements.DateTimeElement;
    public endtime!: Elements.DateTimeElement;
    public room!: Elements.TextElement;
    public content!: Elements.RichTextElement;
}
